### PR TITLE
Add note about log levels

### PR DESCRIPTION
**Pull request by njam**
@tomaszdurka @vogdb @fvovan please review

### CODE REVIEW

**Comment by vogdb** [comment]
**critical** and not **fatal**?

**Comment by njam** [comment]
You're right. Updated with what we're actually using.

**Comment by vogdb** [comment]
Oh. A forced push :) You have my lgtm!

**Comment by njam** [comment]
@tomaszdurka @fvovan wdyt?

**Comment by fvovan** [comment]
Hmm. here it's `critical` https://github.com/cargomedia/cm/pull/2081

**Comment by njam** [comment]
We're streamlining levels automatically in fluentd, see [filter_streamline_level.pp](https://github.com/cargomedia/puppet-packages/blob/master/modules/fluentd/manifests/config/filter_streamline_level.pp), so it's fine.
What we document here are the "canonical" names that we use in the output.

@tomaszdurka @fvovan you agree with the definitions?

**Comment by fvovan** [comment]
lgtm, 
I can add that production loggers should be always (with exception for emergency debug) set up to level greater or equal to `INFO`

**Comment by tomaszdurka** [comment]
👍

**Comment by njam** [comment]
Added a note:
> Typically production deployments will log entries starting at level info or warning.

**Comment by njam** [comment]
@cargomedia/dev please take note of the following definition of log levels:
Level
-----
Log entries should include a `level`:
- **debug**: Low level information about the program, that is mainly useful in a development environment.
- **info**: Important information about the main business logic of the program.
- **warning**: Problems that can appear from time to time, like communication with external services. Their overall volume should be observed to detect anomalies.
- **error**: Problems that should not usually happen. They should be investigated case-by-case.
- **fatal**: Things that should never happen, like uncaught exceptions. These are bugs and should be fixed.

Typically production deployments will log entries starting at level *info* or *warning*.

https://github.com/cargomedia/guides/tree/master/logging#level

**Pull request merged**
