### PR TITLE
SI units

### PR DESCRIPTION
**Pull request by njam**
@vogdb @tomaszdurka please review

### CODE REVIEW

**Comment by njam** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Ok, is this about having miliseconds in js configs? Let's say it's good!

**Comment by vogdb** [comment]
> Ok, is this about having miliseconds in js configs?

rather having seconds

**Comment by tomaszdurka** [comment]
> > Ok, is this about having miliseconds in js configs?

> rather having seconds

I mean having or not having :)

**Pull request merged**
