### PR TITLE
Adjust app release notes

### PR DESCRIPTION
**Pull request by njam**
@kris-lab @ppp0 
The hubot-pulsar deployment process seems quite stable and I suggest we allow all SK developers to initiate a deployment.
What do you think?

cc @tomaszdurka @vogdb

### CODE REVIEW

**Comment by vogdb** [comment]
During rare deployments we have encountered situations when build failed. SK devs don't have access to infrastructure, so they can revert the build or recover it somehow. I'm up for those changes but with condition that we add a possibility to revert the release by cargobot.

**Comment by ppp0** [comment]
may be categorize deployments which do not need schema changes / db scripts to be invoked?

**Comment by njam** [comment]
Agree! Let's add:
- deploy:rollback: https://github.com/cargomedia/hubot-pulsar/issues/26
- deploy:restart: https://github.com/cargomedia/hubot-pulsar/issues/27

**Comment by njam** [comment]
"rollback" and "restart" are added, thanks Aleksei!

@kris-lab @ppp0 ready to roll?

**Comment by kris-lab** [comment]
well, I have no opinion for now. In general I don't have to good feeling about that, but let's so how it works in critical moments when really we have performance drop, db mess etc :)

**Comment by ppp0** [comment]
I'm ok with that - so far experience is ok.. We can never exclude edge cases we don't even know about yet..

**Comment by njam** [comment]
@cargomedia/dev good news! From now on all developers can **deploy their SK changes themselves**!

The goal is that you can and *should* release your changes independently at the moment that suits *you*. Please make aggressive use of that, and try to keep big pending changes on master to a minimum! Release often!

With great power comes great responsibility.
- Change-owners should be available during the release, or somebody who can cover them.
- **Release-initiator is ultimately responsible for understanding, checking and monitoring the impact of the release.**
- After the release, please monitor infrastructure performance, application performance and logs.

See https://github.com/cargomedia/guides/tree/master/workflow#app-release

**Pull request merged**
