### PR TITLE
Add guidelines for software projects/repos

### PR DESCRIPTION
**Pull request by njam**
@tomaszdurka @vogdb wdyt?

### CODE REVIEW

**Comment by vogdb** [comment]
I am not expert in writing but is it a `copy right` and not `copyright` ? Also about `Cargo Media`

**Comment by njam** [comment]
True, "copright", but "cargo media". Amended.

**Comment by vogdb** [comment]
lgtm

**Comment by njam** [comment]
@tomaszdurka wdyt?

**Comment by tomaszdurka** [comment]
looks good :)

**Comment by njam** [comment]
@cargomedia/dev please take a look at some basic guidelines for new software repositories:
https://github.com/njam/guides/blob/repo/software-projects/README.md

**Pull request merged**
