### PR TITLE
Expand code review notes

### PR DESCRIPTION
**Pull request by njam**
See also https://github.com/thoughtbot/guides/tree/master/code-review

### CODE REVIEW

**Comment by njam** [comment]
@alexispeter @zazabe wdyt?

**Comment by njam** [comment]
@alexispeter @zazabe wdyt?

**Comment by alexispeter** [comment]
sounds good

**Comment by zazabe** [comment]
👍

**Comment by njam** [comment]
@cargomedia/dev I've added some notes about code reviews to the guides.
Most of it is obvious and we're doing it already, but it's still good to note it down.
Please remember to make it *easy* for the reviewer to understand the *rationale* of a change and any design decisions you made.


## Code Reviews

Code reviews help keeping **code quality** high, they help **avoiding bugs** land in production and they help to **share knowledge**.

As an author, please take the time to make sure the reviewer can understand the change quickly.
It helps to document the **rationale** behind a change and any **non-obvious decisions** you took (like performance considerations).

Easy to understand commit messages make your change easier to review.
Consider **rewriting your branch's history** if it's messy before asking for a review.
[Rebasing, squashing, amending](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history) are simple tools to create an easy-to-read history.


Procedure:
- Owner asks for review.
- Reviewer verifies changes. *Is it tested? Is it performant? Is it maintainable and extensible?*
- Owner merges, releases and verifies changes.

The owner and the reviewer are responsible for the change and understand its consequences.

**Pull request merged**
