### PR TITLE
Add metaInfo to exception log entry

### PR DESCRIPTION
**Pull request by njam**
@fvovan @tomaszdurka wdyt?

Related to https://github.com/cargomedia/cm/pull/2243

### CODE REVIEW

**Comment by fvovan** [comment]
I not  sure about key naming, may be it would be better to use some non intersected with extra parameters like `metaKey1`, `metaKey2`
And the second thing is mentioned in cargomedia/cm#2243 additional quoting,  should we somehow reflect it here?

**Comment by njam** [comment]
Paired with Tomasz.
@fvovan please check

**Comment by njam** [comment]
Quotes or not is not relevant on the schema level imo.

**Comment by fvovan** [comment]
lgtm

**Pull request merged**
