### PR TITLE
Add mobile development notes

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by njam** [comment]
@ppp0 @vogdb please review

I moved each tool's docu into a separate file for better structuring, and then added a new file `mobile-web-development.md` with some info I learned today.

**Comment by ppp0** [comment]
lgtm

**Comment by vogdb** [comment]
lgtm

**Comment by njam** [comment]
@cargomedia/dev I added some notes about web development/debugging on mobile phones:
https://github.com/cargomedia/guides/blob/master/tools/mobile-web-development.md

Let's collect any non-obvious tricks and tipps there.

**Pull request merged**
